### ISSUE TITLE
Angle snapping in Transform Settings

### ISSUE THREAD

**Issue by Cgameworld** [Cgameworld/TrafficLightReplacer#17]
Snap to multiples of 45 degrees or to bigger/smaller increments? Thoughts?

**Comment by Cgameworld** [comment]
Snap to multiples of 45 degrees? 

Thoughts - should it be in bigger or smaller increments?

**Comment by algernon-A** [comment]
If you want to rotate traffic lights, then you're probably fine-tuning precise placements (e.g. to particular corner situations or unusual intersection formats).  In such cases, 45 degrees would be too coarse - 5 degrees maybe?

**Comment by Cgameworld** [comment]
Currently the slider has an interval of 1 degree, was thinking to continue having it like that, but have the slider snap when it is dragged near a common interval. For example, when the slider is at/after 43 it snaps to 45

**Comment by algernon-A** [comment]
Could work - or maybe hold down a modifier key or press a toggle to enable snapping?  I imagine some users will want control down to the degree, but for others nearest interval of 5?

**Comment by Cgameworld** [comment]
added in 838bb893638bae454e429ec96ef8c6dd550c0154
