### ISSUE TITLE
Not working on all roads/junctions

### ISSUE THREAD

**Issue by chameleon-tbn** [Cgameworld/TrafficLightReplacer#19]
First thanks for this great mod! It already make a lot of stuff much nicer.
But i have several junctions/roads the traffic lights are not exchanged - i would say these are ale custom/workshop roads.

![image](https://user-images.githubusercontent.com/37211016/93026088-a910b280-f603-11ea-9f28-14b35bc362bc.png)

**Comment by Cgameworld** [comment]
Thanks! Replacing non vanilla lights is a planned feature but it will probably not be implemented on the initial release

**Comment by chameleon-tbn** [comment]
Hi @Cgameworld no, you got it wrong (allthough i'll love to see the feature you've described too :) ): These are custom roads that have normal vanilla traffic lights and with your traffic lights replacer on one of the roads (the large main road) i could exchange to clus traffic lights but  the smaller (custom workshop) road kept the vanilla traffic lights...

**Comment by Cgameworld** [comment]
@thebugfixnet What is the name of the custom workshop road(s) where you are experiencing￼ the vanilla lights not being replaced?

**Comment by chameleon-tbn** [comment]
sorry for beeing late on this:

e.g.:
https://steamcommunity.com/sharedfiles/filedetails/?id=2190481757
https://steamcommunity.com/sharedfiles/filedetails/?id=2131872797
https://steamcommunity.com/sharedfiles/filedetails/?id=2098394897

**Comment by Cgameworld** [comment]
@chameleon-tbn The problems should be fixed in the latest commit, pushed an update to the beta workshop listing
Can you test it again to see if the issue still appears on your end?

**Comment by chameleon-tbn** [comment]
@Cgameworld *subbed* and testing now :)

**Comment by chameleon-tbn** [comment]
@Cgameworld works as expected :) All roads i use have now the exchanged traffic lights.  Thanks for the fix!

What is that top button doing?
![image](https://user-images.githubusercontent.com/37211016/99798154-c9437d00-2b30-11eb-9b33-7665d7c954ec.png)


btw is it possible to chat with you over discord? Would make some things easier that i would like to talk with you about :)

**Comment by Cgameworld** [comment]
@chameleon-tbn Cool, glad it is working

That button is for debugging, basically it finds which nodes have t-intersections and outputs the node id(s) in the ModTools console. It's the first step in fixing the t-intersection issue, not going to be in the final release obviously

Sure, my discord username is Cgameworld#3716
